# Generated by Django 5.0.4 on 2024-05-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sex',
            field=models.CharField(choices=[('participator', 'Участник'), ('tutor', 'Тьютор'), ('supervisor', 'Наставник'), ('areacurator', 'Куратор направления'), ('coordinator', 'Координатор проекта'), ('zamruk', 'Заместитель руководителя проекта'), ('master', 'Руководитель проекта')], default='male', max_length=12, verbose_name='sex'),
        ),
    ]
