# Generated by Django 5.0.4 on 2024-05-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customuser_groups_alter_customuser_sex_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='curdir',
        ),
        migrations.AddField(
            model_name='customuser',
            name='curdir',
            field=models.ManyToManyField(blank=True, to='main.curdirs'),
        ),
    ]
