# Generated by Django 5.0.4 on 2024-05-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_studyplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='messenger',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='messenger',
            name='sticker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='messenger',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
