# Generated by Django 5.0.4 on 2024-05-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_messenger_file_messenger_sticker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messenger',
            name='sticker',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
