# Generated by Django 5.0.4 on 2024-05-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_messenger_sticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='test',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tests',
            name='tutor',
        ),
        migrations.AddField(
            model_name='tasks',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tasks/'),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='Tests',
        ),
    ]
