# Generated by Django 5.0.4 on 2024-05-17 14:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_questions_test_remove_tests_task_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='student',
        ),
        migrations.AddField(
            model_name='tasks',
            name='students',
            field=models.ManyToManyField(related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
