# Generated by Django 5.0.4 on 2024-05-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_tasks_student_tasks_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('participator', 'Участник'), ('tutor', 'Тьютор'), ('supervisor', 'Наставник'), ('areacurator', 'Куратор направления'), ('coordinator', 'Координатор проекта'), ('zamruk', 'Заместитель руководителя проекта'), ('master', 'Руководитель проекта'), ('newscreator', 'Новостник')], default='participator', max_length=50, verbose_name='role'),
        ),
    ]
