# Generated by Django 5.0.4 on 2024-05-19 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_newsimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_tutors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tutorstudent',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
