# Generated by Django 5.0.4 on 2024-05-19 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_tasksubmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='main.tasks'),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
