# Generated by Django 5.0.4 on 2024-05-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_tasksubmission_task_alter_tasksubmission_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lives',
            field=models.IntegerField(default=3),
        ),
    ]
